name: display hello world
 
on: 
  push:
    branches:
      [master]
  pull_request:
    branches:
      [master]

jobs:
    hello:
       runs-on: ubuntu-latest

       steps:
          - name: checkout repo
            uses: actions/checkout@v4


          - name: say hello
            run: echo 'hello'

          - name: user checkout
            run: whoami